### ISSUE TITLE
Further details regarding the installation process

### ISSUE THREAD

**Issue by kidpaul94** [ian-chuang/Manipulator-Mujoco#1]
Hello,

Thank you for sharing this nice repository. I would like to ask a question regarding the installation process as I have encountered several bumps while following the given instruction. **Which mujoco version did you use for developing this repository**? Is it the one that has been maintained by Google Deepmind? `pip install -e .` only installs the python-bind.

Thanks

**Comment by kidpaul94** [comment]
When I tried to run the demo in Ubuntu 22.04, it caused several errors. However, **on Ubuntu 20.04**, everything was smooth. So, I'll just close this issue. Note that this repository has dependency on gymnasium, which would be helpful to include in requirements.txt.

**Comment by ian-chuang** [comment]
Hello, I'd recommend using Anaconda or venv to install the python dependencies if you haven't already. I think you can just use the latest version of mujoco and dm_control but feel free to share the errors you had. I believe doing pip install mujoco is all you need since it will install the entire simulator + latest version.

Thanks, I updated the requirements.txt
